### ISSUE TITLE
Is this what it does? Or not...?

### ISSUE THREAD

**Issue by Ander3232** [jeetee/MuseScore_Timesig_Enforcer#1]
What does this plugin actually do? The "documentation" is very vague—all it says is:

> Clip or Expand measures to fit their current time signature.

I changed a time signature from 3/4 to 6/8, and MS didn't change the notes' time values to conform with the signature (it left bars of three quarter notes each, rather than doubling them to bars of six eighth notes). So I thought that if I installed this plugin, then selected the whole score and ran it, it might do what I've just described. (How else could measures "be expanded to fit their time signature"?) But nothing happens.  🤷‍♂️

Maybe you could be a bit more specific, for us non-psychic users? Thanks!

**Comment by jeetee** [comment]
MuseScore allows you by a number of methods to create measures that have a different duration than what the time signature shows (insert mode, joining measures, removing time). It (by default) indicates this by showing a small + or - sign above the measure.

What this plugin does is clip or expand those irregular measures back to conform to the time signature (it thus changes the actual duration of the measure). If a measure was too short prior to the plugin running, rests will be inserted. If the measure was too long prior to the plugin running, notes will be dropped/shortened as a result.

What you are looking for (doubling note values) is a built-in function to be found under Edit > Paste double duration: see https://musescore.org/en/handbook/3/copy-and-paste#paste-half-double-duration for instruction about that.
